services:
  front:
    build: .
    tty: true
    ports:
      - "3001:3000"
      - "4000:4000"
    volumes:
      - ./next_app:/usr/src/app
    environment:
      - WATCHPACK_POLLING=true
    command:
      sh -c "bun install && bun run dev"